theme: jekyll-theme-minimal
theme: jekyll-theme-minimal
title: Ying Li <anything you like>
description: portfolio of my work

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
